/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.carbondata.core.dictionary.generator.key;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto
public final class DictionaryKeyProto {
  private DictionaryKeyProto() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface keyReqOrBuilder extends
          // @@protoc_insertion_point(interface_extends:protobuf.keyReq)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    boolean hasTableUniqueName();
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    java.lang.String getTableUniqueName();
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    com.google.protobuf.ByteString
    getTableUniqueNameBytes();

    /**
     * <code>required string columnName = 2;</code>
     */
    boolean hasColumnName();
    /**
     * <code>required string columnName = 2;</code>
     */
    java.lang.String getColumnName();
    /**
     * <code>required string columnName = 2;</code>
     */
    com.google.protobuf.ByteString
    getColumnNameBytes();

    /**
     * <code>required string dataVal = 3;</code>
     */
    boolean hasDataVal();
    /**
     * <code>required string dataVal = 3;</code>
     */
    java.lang.String getDataVal();
    /**
     * <code>required string dataVal = 3;</code>
     */
    com.google.protobuf.ByteString
    getDataValBytes();

    /**
     * <code>required string type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 4;</code>
     */
    com.google.protobuf.ByteString
    getTypeBytes();

    /**
     * <code>required string threadNo = 5;</code>
     */
    boolean hasThreadNo();
    /**
     * <code>required string threadNo = 5;</code>
     */
    java.lang.String getThreadNo();
    /**
     * <code>required string threadNo = 5;</code>
     */
    com.google.protobuf.ByteString
    getThreadNoBytes();
  }
  /**
   * Protobuf type {@code protobuf.keyReq}
   *
   * <pre>
   * (1)
   * </pre>
   */
  public static final class keyReq extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:protobuf.keyReq)
          keyReqOrBuilder {
    // Use keyReq.newBuilder() to construct.
    private keyReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private keyReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final keyReq defaultInstance;
    public static keyReq getDefaultInstance() {
      return defaultInstance;
    }

    public keyReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private keyReq(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              tableUniqueName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              columnName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dataVal_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              type_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              threadNo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return DictionaryKeyProto.internal_static_protobuf_keyReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return DictionaryKeyProto.internal_static_protobuf_keyReq_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      DictionaryKeyProto.keyReq.class, DictionaryKeyProto.keyReq.Builder.class);
    }

    public static com.google.protobuf.Parser<keyReq> PARSER =
            new com.google.protobuf.AbstractParser<keyReq>() {
              public keyReq parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new keyReq(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<keyReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TABLEUNIQUENAME_FIELD_NUMBER = 1;
    private java.lang.Object tableUniqueName_;
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    public boolean hasTableUniqueName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    public java.lang.String getTableUniqueName() {
      java.lang.Object ref = tableUniqueName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tableUniqueName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    public com.google.protobuf.ByteString
    getTableUniqueNameBytes() {
      java.lang.Object ref = tableUniqueName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        tableUniqueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNNAME_FIELD_NUMBER = 2;
    private java.lang.Object columnName_;
    /**
     * <code>required string columnName = 2;</code>
     */
    public boolean hasColumnName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string columnName = 2;</code>
     */
    public java.lang.String getColumnName() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          columnName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string columnName = 2;</code>
     */
    public com.google.protobuf.ByteString
    getColumnNameBytes() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        columnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAVAL_FIELD_NUMBER = 3;
    private java.lang.Object dataVal_;
    /**
     * <code>required string dataVal = 3;</code>
     */
    public boolean hasDataVal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string dataVal = 3;</code>
     */
    public java.lang.String getDataVal() {
      java.lang.Object ref = dataVal_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataVal_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dataVal = 3;</code>
     */
    public com.google.protobuf.ByteString
    getDataValBytes() {
      java.lang.Object ref = dataVal_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        dataVal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private java.lang.Object type_;
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
    getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THREADNO_FIELD_NUMBER = 5;
    private java.lang.Object threadNo_;
    /**
     * <code>required string threadNo = 5;</code>
     */
    public boolean hasThreadNo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string threadNo = 5;</code>
     */
    public java.lang.String getThreadNo() {
      java.lang.Object ref = threadNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          threadNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string threadNo = 5;</code>
     */
    public com.google.protobuf.ByteString
    getThreadNoBytes() {
      java.lang.Object ref = threadNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        threadNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tableUniqueName_ = "";
      columnName_ = "";
      dataVal_ = "";
      type_ = "";
      threadNo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTableUniqueName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumnName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThreadNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTableUniqueNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getColumnNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataValBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getThreadNoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, getTableUniqueNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, getColumnNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getDataValBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(4, getTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(5, getThreadNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DictionaryKeyProto.keyReq parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DictionaryKeyProto.keyReq parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DictionaryKeyProto.keyReq parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DictionaryKeyProto.keyReq parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DictionaryKeyProto.keyReq parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DictionaryKeyProto.keyReq parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DictionaryKeyProto.keyReq parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DictionaryKeyProto.keyReq parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DictionaryKeyProto.keyReq parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DictionaryKeyProto.keyReq parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DictionaryKeyProto.keyReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.keyReq}
     *
     * <pre>
     * (1)
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protobuf.keyReq)
            DictionaryKeyProto.keyReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return DictionaryKeyProto.internal_static_protobuf_keyReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return DictionaryKeyProto.internal_static_protobuf_keyReq_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        DictionaryKeyProto.keyReq.class, DictionaryKeyProto.keyReq.Builder.class);
      }

      // Construct using org.apache.carbondata.core.dictionary.generator.key.Protobuf.keyReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tableUniqueName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        columnName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dataVal_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        threadNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return DictionaryKeyProto.internal_static_protobuf_keyReq_descriptor;
      }

      public DictionaryKeyProto.keyReq getDefaultInstanceForType() {
        return DictionaryKeyProto.keyReq.getDefaultInstance();
      }

      public DictionaryKeyProto.keyReq build() {
        DictionaryKeyProto.keyReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DictionaryKeyProto.keyReq buildPartial() {
        DictionaryKeyProto.keyReq result = new DictionaryKeyProto.keyReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tableUniqueName_ = tableUniqueName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.columnName_ = columnName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataVal_ = dataVal_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.threadNo_ = threadNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DictionaryKeyProto.keyReq) {
          return mergeFrom((DictionaryKeyProto.keyReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DictionaryKeyProto.keyReq other) {
        if (other == DictionaryKeyProto.keyReq.getDefaultInstance()) return this;
        if (other.hasTableUniqueName()) {
          bitField0_ |= 0x00000001;
          tableUniqueName_ = other.tableUniqueName_;
          onChanged();
        }
        if (other.hasColumnName()) {
          bitField0_ |= 0x00000002;
          columnName_ = other.columnName_;
          onChanged();
        }
        if (other.hasDataVal()) {
          bitField0_ |= 0x00000004;
          dataVal_ = other.dataVal_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000008;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasThreadNo()) {
          bitField0_ |= 0x00000010;
          threadNo_ = other.threadNo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTableUniqueName()) {

          return false;
        }
        if (!hasColumnName()) {

          return false;
        }
        if (!hasDataVal()) {

          return false;
        }
        if (!hasType()) {

          return false;
        }
        if (!hasThreadNo()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        DictionaryKeyProto.keyReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DictionaryKeyProto.keyReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object tableUniqueName_ = "";
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public boolean hasTableUniqueName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public java.lang.String getTableUniqueName() {
        java.lang.Object ref = tableUniqueName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tableUniqueName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public com.google.protobuf.ByteString
      getTableUniqueNameBytes() {
        java.lang.Object ref = tableUniqueName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          tableUniqueName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public Builder setTableUniqueName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tableUniqueName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public Builder clearTableUniqueName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tableUniqueName_ = getDefaultInstance().getTableUniqueName();
        onChanged();
        return this;
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public Builder setTableUniqueNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tableUniqueName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object columnName_ = "";
      /**
       * <code>required string columnName = 2;</code>
       */
      public boolean hasColumnName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public java.lang.String getColumnName() {
        java.lang.Object ref = columnName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            columnName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public com.google.protobuf.ByteString
      getColumnNameBytes() {
        java.lang.Object ref = columnName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          columnName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public Builder setColumnName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        columnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public Builder clearColumnName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        columnName_ = getDefaultInstance().getColumnName();
        onChanged();
        return this;
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public Builder setColumnNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        columnName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataVal_ = "";
      /**
       * <code>required string dataVal = 3;</code>
       */
      public boolean hasDataVal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string dataVal = 3;</code>
       */
      public java.lang.String getDataVal() {
        java.lang.Object ref = dataVal_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataVal_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dataVal = 3;</code>
       */
      public com.google.protobuf.ByteString
      getDataValBytes() {
        java.lang.Object ref = dataVal_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          dataVal_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dataVal = 3;</code>
       */
      public Builder setDataVal(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        dataVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dataVal = 3;</code>
       */
      public Builder clearDataVal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataVal_ = getDefaultInstance().getDataVal();
        onChanged();
        return this;
      }
      /**
       * <code>required string dataVal = 3;</code>
       */
      public Builder setDataValBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        dataVal_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
      getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setType(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setTypeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object threadNo_ = "";
      /**
       * <code>required string threadNo = 5;</code>
       */
      public boolean hasThreadNo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public java.lang.String getThreadNo() {
        java.lang.Object ref = threadNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            threadNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public com.google.protobuf.ByteString
      getThreadNoBytes() {
        java.lang.Object ref = threadNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          threadNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public Builder setThreadNo(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        threadNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public Builder clearThreadNo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        threadNo_ = getDefaultInstance().getThreadNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public Builder setThreadNoBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        threadNo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.keyReq)
    }

    static {
      defaultInstance = new keyReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.keyReq)
  }

  public interface keyRespOrBuilder extends
          // @@protoc_insertion_point(interface_extends:protobuf.keyResp)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    boolean hasTableUniqueName();
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    java.lang.String getTableUniqueName();
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    com.google.protobuf.ByteString
    getTableUniqueNameBytes();

    /**
     * <code>required string columnName = 2;</code>
     */
    boolean hasColumnName();
    /**
     * <code>required string columnName = 2;</code>
     */
    java.lang.String getColumnName();
    /**
     * <code>required string columnName = 2;</code>
     */
    com.google.protobuf.ByteString
    getColumnNameBytes();

    /**
     * <code>required int32 dataKey = 3;</code>
     */
    boolean hasDataKey();
    /**
     * <code>required int32 dataKey = 3;</code>
     */
    int getDataKey();

    /**
     * <code>required string type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 4;</code>
     */
    com.google.protobuf.ByteString
    getTypeBytes();

    /**
     * <code>required string threadNo = 5;</code>
     */
    boolean hasThreadNo();
    /**
     * <code>required string threadNo = 5;</code>
     */
    java.lang.String getThreadNo();
    /**
     * <code>required string threadNo = 5;</code>
     */
    com.google.protobuf.ByteString
    getThreadNoBytes();
  }
  /**
   * Protobuf type {@code protobuf.keyResp}
   *
   * <pre>
   *(2)
   * </pre>
   */
  public static final class keyResp extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:protobuf.keyResp)
          keyRespOrBuilder {
    // Use keyResp.newBuilder() to construct.
    private keyResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private keyResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final keyResp defaultInstance;
    public static keyResp getDefaultInstance() {
      return defaultInstance;
    }

    public keyResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private keyResp(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              tableUniqueName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              columnName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              dataKey_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              type_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              threadNo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return DictionaryKeyProto.internal_static_protobuf_keyResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return DictionaryKeyProto.internal_static_protobuf_keyResp_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      DictionaryKeyProto.keyResp.class, DictionaryKeyProto.keyResp.Builder.class);
    }

    public static com.google.protobuf.Parser<keyResp> PARSER =
            new com.google.protobuf.AbstractParser<keyResp>() {
              public keyResp parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new keyResp(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<keyResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TABLEUNIQUENAME_FIELD_NUMBER = 1;
    private java.lang.Object tableUniqueName_;
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    public boolean hasTableUniqueName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    public java.lang.String getTableUniqueName() {
      java.lang.Object ref = tableUniqueName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tableUniqueName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tableUniqueName = 1;</code>
     */
    public com.google.protobuf.ByteString
    getTableUniqueNameBytes() {
      java.lang.Object ref = tableUniqueName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        tableUniqueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNNAME_FIELD_NUMBER = 2;
    private java.lang.Object columnName_;
    /**
     * <code>required string columnName = 2;</code>
     */
    public boolean hasColumnName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string columnName = 2;</code>
     */
    public java.lang.String getColumnName() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          columnName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string columnName = 2;</code>
     */
    public com.google.protobuf.ByteString
    getColumnNameBytes() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        columnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAKEY_FIELD_NUMBER = 3;
    private int dataKey_;
    /**
     * <code>required int32 dataKey = 3;</code>
     */
    public boolean hasDataKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 dataKey = 3;</code>
     */
    public int getDataKey() {
      return dataKey_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private java.lang.Object type_;
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
    getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THREADNO_FIELD_NUMBER = 5;
    private java.lang.Object threadNo_;
    /**
     * <code>required string threadNo = 5;</code>
     */
    public boolean hasThreadNo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string threadNo = 5;</code>
     */
    public java.lang.String getThreadNo() {
      java.lang.Object ref = threadNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          threadNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string threadNo = 5;</code>
     */
    public com.google.protobuf.ByteString
    getThreadNoBytes() {
      java.lang.Object ref = threadNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        threadNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tableUniqueName_ = "";
      columnName_ = "";
      dataKey_ = 0;
      type_ = "";
      threadNo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTableUniqueName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumnName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThreadNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTableUniqueNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getColumnNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, dataKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getThreadNoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, getTableUniqueNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, getColumnNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, dataKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(4, getTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(5, getThreadNoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DictionaryKeyProto.keyResp parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DictionaryKeyProto.keyResp parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DictionaryKeyProto.keyResp parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DictionaryKeyProto.keyResp parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DictionaryKeyProto.keyResp parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DictionaryKeyProto.keyResp parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DictionaryKeyProto.keyResp parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DictionaryKeyProto.keyResp parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DictionaryKeyProto.keyResp parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DictionaryKeyProto.keyResp parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DictionaryKeyProto.keyResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.keyResp}
     *
     * <pre>
     *(2)
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protobuf.keyResp)
            DictionaryKeyProto.keyRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return DictionaryKeyProto.internal_static_protobuf_keyResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return DictionaryKeyProto.internal_static_protobuf_keyResp_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        DictionaryKeyProto.keyResp.class, DictionaryKeyProto.keyResp.Builder.class);
      }

      // Construct using org.apache.carbondata.core.dictionary.generator.key.Protobuf.keyResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tableUniqueName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        columnName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dataKey_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        threadNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return DictionaryKeyProto.internal_static_protobuf_keyResp_descriptor;
      }

      public DictionaryKeyProto.keyResp getDefaultInstanceForType() {
        return DictionaryKeyProto.keyResp.getDefaultInstance();
      }

      public DictionaryKeyProto.keyResp build() {
        DictionaryKeyProto.keyResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DictionaryKeyProto.keyResp buildPartial() {
        DictionaryKeyProto.keyResp result = new DictionaryKeyProto.keyResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tableUniqueName_ = tableUniqueName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.columnName_ = columnName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataKey_ = dataKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.threadNo_ = threadNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DictionaryKeyProto.keyResp) {
          return mergeFrom((DictionaryKeyProto.keyResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DictionaryKeyProto.keyResp other) {
        if (other == DictionaryKeyProto.keyResp.getDefaultInstance()) return this;
        if (other.hasTableUniqueName()) {
          bitField0_ |= 0x00000001;
          tableUniqueName_ = other.tableUniqueName_;
          onChanged();
        }
        if (other.hasColumnName()) {
          bitField0_ |= 0x00000002;
          columnName_ = other.columnName_;
          onChanged();
        }
        if (other.hasDataKey()) {
          setDataKey(other.getDataKey());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000008;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasThreadNo()) {
          bitField0_ |= 0x00000010;
          threadNo_ = other.threadNo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTableUniqueName()) {

          return false;
        }
        if (!hasColumnName()) {

          return false;
        }
        if (!hasDataKey()) {

          return false;
        }
        if (!hasType()) {

          return false;
        }
        if (!hasThreadNo()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        DictionaryKeyProto.keyResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DictionaryKeyProto.keyResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object tableUniqueName_ = "";
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public boolean hasTableUniqueName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public java.lang.String getTableUniqueName() {
        java.lang.Object ref = tableUniqueName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tableUniqueName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public com.google.protobuf.ByteString
      getTableUniqueNameBytes() {
        java.lang.Object ref = tableUniqueName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          tableUniqueName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public Builder setTableUniqueName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tableUniqueName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public Builder clearTableUniqueName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tableUniqueName_ = getDefaultInstance().getTableUniqueName();
        onChanged();
        return this;
      }
      /**
       * <code>required string tableUniqueName = 1;</code>
       */
      public Builder setTableUniqueNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tableUniqueName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object columnName_ = "";
      /**
       * <code>required string columnName = 2;</code>
       */
      public boolean hasColumnName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public java.lang.String getColumnName() {
        java.lang.Object ref = columnName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            columnName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public com.google.protobuf.ByteString
      getColumnNameBytes() {
        java.lang.Object ref = columnName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          columnName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public Builder setColumnName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        columnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public Builder clearColumnName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        columnName_ = getDefaultInstance().getColumnName();
        onChanged();
        return this;
      }
      /**
       * <code>required string columnName = 2;</code>
       */
      public Builder setColumnNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        columnName_ = value;
        onChanged();
        return this;
      }

      private int dataKey_ ;
      /**
       * <code>required int32 dataKey = 3;</code>
       */
      public boolean hasDataKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 dataKey = 3;</code>
       */
      public int getDataKey() {
        return dataKey_;
      }
      /**
       * <code>required int32 dataKey = 3;</code>
       */
      public Builder setDataKey(int value) {
        bitField0_ |= 0x00000004;
        dataKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 dataKey = 3;</code>
       */
      public Builder clearDataKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataKey_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
      getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setType(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setTypeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object threadNo_ = "";
      /**
       * <code>required string threadNo = 5;</code>
       */
      public boolean hasThreadNo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public java.lang.String getThreadNo() {
        java.lang.Object ref = threadNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            threadNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public com.google.protobuf.ByteString
      getThreadNoBytes() {
        java.lang.Object ref = threadNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          threadNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public Builder setThreadNo(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        threadNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public Builder clearThreadNo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        threadNo_ = getDefaultInstance().getThreadNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string threadNo = 5;</code>
       */
      public Builder setThreadNoBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        threadNo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.keyResp)
    }

    static {
      defaultInstance = new keyResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.keyResp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_protobuf_keyReq_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_protobuf_keyReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_protobuf_keyResp_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_protobuf_keyResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\016protobuf.proto\022\010protobuf\"f\n\006keyReq\022\027\n\017" +
                    "tableUniqueName\030\001 \002(\t\022\022\n\ncolumnName\030\002 \002(" +
                    "\t\022\017\n\007dataVal\030\003 \002(\t\022\014\n\004type\030\004 \002(\t\022\020\n\010thre" +
                    "adNo\030\005 \002(\t\"g\n\007keyResp\022\027\n\017tableUniqueName" +
                    "\030\001 \002(\t\022\022\n\ncolumnName\030\002 \002(\t\022\017\n\007dataKey\030\003 " +
                    "\002(\005\022\014\n\004type\030\004 \002(\t\022\020\n\010threadNo\030\005 \002(\tB5\n3o" +
                    "rg.apache.carbondata.core.dictionary.gen" +
                    "erator.key"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_protobuf_keyReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_keyReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_protobuf_keyReq_descriptor,
            new java.lang.String[] { "TableUniqueName", "ColumnName", "DataVal", "Type", "ThreadNo", });
    internal_static_protobuf_keyResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_keyResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_protobuf_keyResp_descriptor,
            new java.lang.String[] { "TableUniqueName", "ColumnName", "DataKey", "Type", "ThreadNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)

  /**
   * dictionaryKey to keyResp
   *
   * @param key
   * @return
   */
  public static keyResp keyToResp(DictionaryKey key) {
    keyResp resp = keyResp.newBuilder()
            .setTableUniqueName(key.getTableUniqueName())
            .setColumnName(key.getColumnName())
            .setDataKey((Integer) key.getData())
            .setType(key.getType())
            .setThreadNo(key.getThreadNo())
            .build();
    return resp;
  }

  /**
   * keyResp to dictionaryKey
   *
   * @param resp
   * @return
   */
  public static DictionaryKey respToKey(keyResp resp) {
    DictionaryKey key = new DictionaryKey();
    key.setTableUniqueName(resp.getTableUniqueName());
    key.setColumnName(resp.getColumnName());
    key.setData(resp.getDataKey());
    key.setType(resp.getType());
    key.setThreadNo(resp.getThreadNo());
    return key;
  }

  /**
   * dictionaryKey to keyReq
   *
   * @param key
   * @return
   */
  public static keyReq keyToReq(DictionaryKey key) {
    keyReq req = keyReq.newBuilder()
            .setTableUniqueName(key.getTableUniqueName())
            .setColumnName(key.getColumnName())
            .setDataVal(key.getData().toString())
            .setType(key.getType())
            .setThreadNo(key.getThreadNo())
            .build();
    return req;
  }

  /**
   * keyReq to dictionaryKey
   *
   * @param req
   * @return
   */
  public static DictionaryKey reqToKey(keyReq req) {
    DictionaryKey key = new DictionaryKey();
    key.setTableUniqueName(req.getTableUniqueName());
    key.setColumnName(req.getColumnName());
    key.setData(req.getDataVal());
    key.setType(req.getType());
    key.setThreadNo(req.getThreadNo());
    return key;
  }
}
